environment:
  matrix:
  - MSYS_BITS: 64
    CONFIGURE_ARGS: --build=x86_64-pc-windows-msvc

clone_depth: 1
build: false

install:
  - set PATH=C:\msys64\mingw%MSYS_BITS%\bin;C:\msys64\usr\bin;%PATH%

test_script:
  - sh ./configure %CONFIGURE_ARGS%
  - ps: make -j (nproc)
  - ps: make check -j (nproc)

cache:
  - build/%TARGET%/llvm -> src/rustllvm/llvm-auto-clean-trigger
