environment:
  matrix:
  - MSYS_BITS: 64
    CONFIGURE_ARGS: --build=x86_64-pc-windows-msvc
    CHECK: check
  - MSYS_BITS: 64
    CONFIGURE_ARGS: --build=x86_64-pc-windows-msvc --enable-rustbuild
    CHECK: check
  - MSYS_BITS: 64
    CONFIGURE_ARGS: --build=x86_64-pc-windows-msvc --enable-rustbuild
    CHECK: check-cargotest
  - MSYS_BITS: 64
    CONFIGURE_ARGS: --build=x86_64-pc-windows-gnu
    CHECK: check
  - MSYS_BITS: 32
    CONFIGURE_ARGS: --build=i686-pc-windows-msvc
    CHECK: check
  - MSYS_BITS: 32
    CONFIGURE_ARGS: --build=i686-pc-windows-gnu
    CHECK: check
  - MSYS_BITS: 32
    CONFIGURE_ARGS: --build=i686-pc-windows-gnu --enable-rustbuild
    CHECK: check

clone_depth: 1
build: false

install:
  - set PATH=C:\msys64\mingw%MSYS_BITS%\bin;C:\msys64\usr\bin;%PATH%

test_script:
  - sh ./configure %CONFIGURE_ARGS%
  - make -j2
  - make %CHECK% -j2

cache:
  - build/%TARGET%/llvm -> src/rustllvm/llvm-auto-clean-trigger
